'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Macro100={kcal?:number;protein?:number;carbs?:number;fat?:number};
type Item={id?:string;food_name:string;planned_quantity:number|null;actual_quantity:number|null;unit:string|null;source:string;macros_per_100?:Macro100};
type Meal={id:string;meal_key:string;meal_label:string;planned_time:string|null;title:string|null;status:string;daily_plan_id:string};

export default function MealDetail({mealId}:{mealId:string}){
 const supabase=useMemo(()=>createClient(),[]);const[meal,setMeal]=useState<Meal|null>(null);const[items,setItems]=useState<Item[]>([]);const[userId,setUserId]=useState<string|null>(null);const[busy,setBusy]=useState(true);const[message,setMessage]=useState<string|null>(null);
 useEffect(()=>{void(async()=>{const{data:auth}=await supabase.auth.getUser();if(!auth.user){setMessage('Accedi per aprire il pasto.');setBusy(false);return}setUserId(auth.user.id);const{data:mealData,error}=await supabase.from('daily_meals').select('id,meal_key,meal_label,planned_time,title,status,daily_plan_id').eq('id',mealId).maybeSingle();if(error||!mealData){setMessage(error?.message??'Pasto non trovato.');setBusy(false);return}setMeal(mealData as Meal);const{data:existing}=await supabase.from('meal_items').select('id,food_name,planned_quantity,actual_quantity,unit,source,macros_per_100').eq('daily_meal_id',mealId).order('created_at');if(existing?.length){setItems(existing as Item[]);setBusy(false);return}const{data:dp}=await supabase.from('daily_plans').select('nutrition_plan_id').eq('id',mealData.daily_plan_id).maybeSingle();if(dp?.nutrition_plan_id){const{data:plan}=await supabase.from('nutrition_plans').select('raw_extraction').eq('id',dp.nutrition_plan_id).maybeSingle();const parsed=plan?.raw_extraction?.meals?.find((x:any)=>x.key===mealData.meal_key);setItems((parsed?.foods??[]).map((f:any)=>({food_name:f.name,planned_quantity:typeof f.quantity==='number'?f.quantity:null,actual_quantity:typeof f.quantity==='number'?f.quantity:null,unit:f.unit??'g',source:'plan',macros_per_100:f.macros_per_100??{}})))}setBusy(false)})()},[mealId,supabase]);
 const updateItem=(i:number,p:Partial<Item>)=>setItems(c=>c.map((x,n)=>n===i?{...x,...p}:x));
 const updateMacro=(i:number,k:keyof Macro100,v:string)=>setItems(c=>c.map((x,n)=>n===i?{...x,macros_per_100:{...(x.macros_per_100??{}),[k]:v===''?undefined:Number(v)}}:x));
 function addItem(){setItems(c=>[...c,{food_name:'',planned_quantity:null,actual_quantity:null,unit:'g',source:'manual',macros_per_100:{}}])}
 function totals(list:Item[]){return list.reduce((a,x)=>{const q=Number(x.actual_quantity||0);const factor=(x.unit==='g'||x.unit==='ml')?q/100:q;const m=x.macros_per_100??{};a.kcal+=Number(m.kcal||0)*factor;a.protein+=Number(m.protein||0)*factor;a.carbs+=Number(m.carbs||0)*factor;a.fat+=Number(m.fat||0)*factor;return a},{kcal:0,protein:0,carbs:0,fat:0})}
 async function saveMeal(){if(!userId||!meal)return;setBusy(true);setMessage(null);const valid=items.filter(x=>x.food_name.trim());const{error:de}=await supabase.from('meal_items').delete().eq('daily_meal_id',meal.id);if(de){setBusy(false);setMessage(de.message);return}if(valid.length){const{error:ie}=await supabase.from('meal_items').insert(valid.map(x=>({user_id:userId,daily_meal_id:meal.id,food_name:x.food_name.trim(),planned_quantity:x.planned_quantity,actual_quantity:x.actual_quantity,unit:x.unit||'g',source:x.source||'manual',macros_per_100:x.macros_per_100??{}})));if(ie){setBusy(false);setMessage(ie.message);return}}const t=totals(valid);const{error:me}=await supabase.from('daily_meals').update({status:'eaten',actual_macros:{kcal:Math.round(t.kcal),protein:+t.protein.toFixed(1),carbs:+t.carbs.toFixed(1),fat:+t.fat.toFixed(1),extra_items:valid.filter(x=>x.source==='manual').length}}).eq('id',meal.id);setBusy(false);setMessage(me?me.message:'Pasto registrato. Anche gli alimenti fuori piano sono entrati nel bilancio reale della giornata.')}
 if(busy&&!meal)return <main className="mealDetailShell"><section className="mealDetail"><div className="planMessage">Apro il pasto…</div></section></main>;
 const live=totals(items);
 return <main className="mealDetailShell"><section className="mealDetail"><header className="planPageHeader"><a href="/" className="backLink">←</a><h1 className="brand">Miva</h1><span/></header>{meal?<><div className="planIntro"><span className="eyebrow">{meal.planned_time?.slice(0,5)??''}</span><h2>{meal.meal_label}</h2><p>Il piano resta il riferimento. Qui registri ciò che hai mangiato davvero, compresi eventuali alimenti extra.</p></div><div className="mealBalanceMini"><b>Bilancio del pasto</b><span>{Math.round(live.kcal)} kcal · P {live.protein.toFixed(1)} g · C {live.carbs.toFixed(1)} g · G {live.fat.toFixed(1)} g</span></div><div className="mealItemEditor">{items.map((item,index)=><article className={`mealItemRow ${item.source==='manual'?'extraFood':''}`} key={`${item.food_name}-${index}`}><div className="itemSource">{item.source==='manual'?'FUORI PIANO':'DAL PIANO'}</div><input className="foodNameInput" value={item.food_name} placeholder="Alimento" onChange={e=>updateItem(index,{food_name:e.target.value})}/><div className="quantityCompare"><label><span>Piano</span><input type="number" inputMode="decimal" value={item.planned_quantity??''} disabled={item.source==='manual'} onChange={e=>updateItem(index,{planned_quantity:e.target.value===''?null:Number(e.target.value)})}/></label><span className="quantityArrow">→</span><label><span>Mangiato</span><input type="number" inputMode="decimal" value={item.actual_quantity??''} onChange={e=>updateItem(index,{actual_quantity:e.target.value===''?null:Number(e.target.value)})}/></label><select value={item.unit??'g'} onChange={e=>updateItem(index,{unit:e.target.value})}><option value="g">g</option><option value="ml">ml</option><option value="pz">pz</option><option value="fette">fette</option></select></div><div className="macroInputs"><label>kcal/100<input type="number" value={item.macros_per_100?.kcal??''} onChange={e=>updateMacro(index,'kcal',e.target.value)}/></label><label>P<input type="number" value={item.macros_per_100?.protein??''} onChange={e=>updateMacro(index,'protein',e.target.value)}/></label><label>C<input type="number" value={item.macros_per_100?.carbs??''} onChange={e=>updateMacro(index,'carbs',e.target.value)}/></label><label>G<input type="number" value={item.macros_per_100?.fat??''} onChange={e=>updateMacro(index,'fat',e.target.value)}/></label></div></article>)}</div><button className="secondaryAction addMealItem" onClick={addItem}>＋ Ho mangiato anche altro</button><p className="hint">Per un alimento fuori piano puoi inserire i valori nutrizionali per 100 g/ml: Miva li include nel bilancio senza modificare il piano originale.</p><button className="primaryAction saveMealButton" disabled={busy} onClick={()=>void saveMeal()}>{busy?'Salvo…':'Conferma cosa ho mangiato'}</button>{message?<div className="planMessage">{message}</div>:null}</>:<div className="planMessage">{message??'Pasto non trovato.'}</div>}</section></main>}
