'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type ReviewItem={id:string;food_name:string;brand?:string|null;quantity?:number|null;unit?:string|null;nutrition_data?:{kcal?:number;protein?:number;carbs?:number;fat?:number};context?:{meal_label?:string;planned_time?:string;source?:string};status:string;note?:string|null;created_at:string};

export default function NutritionistReview(){
 const supabase=useMemo(()=>createClient(),[]);const[items,setItems]=useState<ReviewItem[]>([]);const[loading,setLoading]=useState(true);const[message,setMessage]=useState<string|null>(null);
 async function load(){const{data:auth}=await supabase.auth.getUser();if(!auth.user){setMessage('Accedi per vedere le domande per il nutrizionista.');setLoading(false);return}const{data,error}=await supabase.from('nutritionist_review_items').select('*').eq('user_id',auth.user.id).order('created_at',{ascending:false});if(error)setMessage(error.message);setItems((data??[]) as ReviewItem[]);setLoading(false)}
 useEffect(()=>{void load()},[supabase]);
 async function remove(id:string){await supabase.from('nutritionist_review_items').delete().eq('id',id);setItems(c=>c.filter(x=>x.id!==id))}
 async function exportPdf(){const { jsPDF }=await import('jspdf');const doc=new jsPDF();doc.setFontSize(18);doc.text('Miva - Da discutere con il nutrizionista',14,18);doc.setFontSize(10);doc.text(`Generato il ${new Date().toLocaleDateString('it-IT')}`,14,25);let y=35;items.forEach((item,index)=>{if(y>260){doc.addPage();y=20}doc.setFontSize(13);doc.text(`${index+1}. ${item.food_name}`,14,y);y+=6;doc.setFontSize(10);const parts=[item.quantity?`Quantità registrata: ${item.quantity} ${item.unit??'g'}`:'Quantità non indicata',item.context?.meal_label?`Pasto: ${item.context.meal_label}`:'',item.context?.planned_time?`Orario: ${String(item.context.planned_time).slice(0,5)}`:''].filter(Boolean);doc.text(parts.join(' · '),14,y);y+=6;const n=item.nutrition_data??{};doc.text(`Valori indicati: ${n.kcal??'-'} kcal/100 · P ${n.protein??'-'} g · C ${n.carbs??'-'} g · G ${n.fat??'-'} g`,14,y);y+=6;doc.text('Domanda: può essere inserito tra le alternative compatibili del piano?',14,y);y+=6;if(item.note){const lines=doc.splitTextToSize(`Nota: ${item.note}`,180);doc.text(lines,14,y);y+=lines.length*5}y+=7});doc.save(`miva-domande-nutrizionista-${new Date().toISOString().slice(0,10)}.pdf`)}
 return <main className="planPageShell"><section className="planPage"><header className="planPageHeader"><a href="/" className="backLink">←</a><h1 className="brand">Miva</h1><span/></header><div className="planIntro"><span className="eyebrow">PER LA PROSSIMA VISITA</span><h2>Da chiedere al nutrizionista</h2><p>Qui Miva raccoglie gli alimenti fuori piano che vuoi sottoporre al professionista. Non vengono aggiunti automaticamente al piano.</p></div>{loading?<div className="planMessage">Carico…</div>:null}{message?<div className="planMessage">{message}</div>:null}<div className="reviewList">{items.length===0&&!loading?<p className="emptyText">Non hai ancora aggiunto alimenti da discutere.</p>:null}{items.map(item=><article className="reviewCard" key={item.id}><div><strong>{item.food_name}</strong><span>{item.quantity?`${item.quantity} ${item.unit??'g'}`:'Quantità non indicata'}{item.context?.meal_label?` · ${item.context.meal_label}`:''}</span></div><div className="reviewMacros"><span>{item.nutrition_data?.kcal??'-'} kcal</span><span>P {item.nutrition_data?.protein??'-'}</span><span>C {item.nutrition_data?.carbs??'-'}</span><span>G {item.nutrition_data?.fat??'-'}</span></div><p>{item.note??'Valutare se può essere inserito tra le alternative del piano nutrizionale.'}</p><button className="textButton" onClick={()=>void remove(item.id)}>Rimuovi</button></article>)}</div>{items.length?<button className="primaryAction" style={{width:'100%',marginTop:16}} onClick={()=>void exportPdf()}>Scarica PDF per il nutrizionista</button>:null}<a href="/plans" className="secondaryAction" style={{display:'block',textAlign:'center',textDecoration:'none',marginTop:10}}>Gestisci versioni del piano</a></section></main>
}
