'use client';
import {useEffect,useMemo,useState} from 'react';import {createClient} from '@/lib/supabase/client';import AppHeader from '@/components/AppHeader';import BottomNav from '@/components/BottomNav';
type Item={id:string;food_name:string;brand:string|null;quantity:number|null;unit:string|null;expires_on:string|null;item_state:string;quantity_confidence:string;use_first:boolean};
export default function PantryView(){const supabase=useMemo(()=>createClient(),[]);const[userId,setUserId]=useState<string|null>(null);const[items,setItems]=useState<Item[]>([]);const[tab,setTab]=useState<'home'|'expiry'|'scans'>('home');const[name,setName]=useState('');const[msg,setMsg]=useState<string|null>(null);
 async function load(uid:string){const{data,error}=await supabase.from('pantry_items').select('id,food_name,brand,quantity,unit,expires_on,item_state,quantity_confidence,use_first').eq('user_id',uid).is('discarded_at',null).order('expires_on',{ascending:true,nullsFirst:false});if(error)setMsg(error.message);setItems((data??[]) as Item[])}
 useEffect(()=>{void(async()=>{const{data:a}=await supabase.auth.getUser();if(a.user){setUserId(a.user.id);await load(a.user.id)}})()},[supabase]);
 async function add(){if(!userId||!name.trim())return;const{error}=await supabase.from('pantry_items').insert({user_id:userId,food_name:name.trim(),item_state:'sealed',quantity_confidence:'unknown',source:'manual'});if(error)setMsg(error.message);else{setName('');await load(userId)}}
 async function finish(item:Item){if(!userId)return;await supabase.from('pantry_items').update({quantity:0,item_state:'finished'}).eq('id',item.id);await supabase.from('shopping_items').insert({user_id:userId,food_name:item.food_name,brand:item.brand,source:'pantry_finished',reason:'Prodotto finito',suggested:true});await load(userId)}
 async function toggleFirst(item:Item){await supabase.from('pantry_items').update({use_first:!item.use_first}).eq('id',item.id);if(userId)await load(userId)}
 const visible=tab==='expiry'?items.filter(i=>i.expires_on):items.filter(i=>i.item_state!=='finished');
 return <main className="shell"><section className="phone withBottomNav"><AppHeader eyebrow="DISPENSA"/><div className="sectionTabs"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>In casa</button><button className={tab==='expiry'?'active':''} onClick={()=>setTab('expiry')}>Scadenze</button><button className={tab==='scans'?'active':''} onClick={()=>setTab('scans')}>Scannerizzati</button></div>{tab==='scans'?<section className="emptyStateCard"><strong>Scannerizzati</strong><p>Lo storico delle scansioni verrà collegato alla Camera/Scanner nel blocco dedicato.</p></section>:<><div className="quickAdd"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Aggiungi ciò che hai comprato"/><button onClick={()=>void add()}>＋</button></div>{msg?<div className="planMessage">{msg}</div>:null}<section className="pantryList">{visible.length?visible.map(i=><article className={`pantryCard ${i.use_first?'useFirst':''}`} key={i.id}><div><span className="eyebrow">{i.item_state.toUpperCase()}</span><h3>{i.food_name}</h3><p>{i.quantity!=null?`${i.quantity} ${i.unit||''}`:i.quantity_confidence==='unknown'?'Quantità da verificare':'Quantità stimata'}{i.expires_on?` · scade ${new Date(i.expires_on+'T12:00:00').toLocaleDateString('it-IT')}`:''}</p></div><div className="miniActions"><button onClick={()=>void toggleFirst(i)}>{i.use_first?'✓ Finisci prima':'Finisci prima'}</button><button onClick={()=>void finish(i)}>È già finito</button></div></article>):<div className="emptyStateCard"><strong>Dispensa vuota.</strong><p>Non serve catalogare tutta la cucina: aggiungila poco alla volta mentre compri e cucini.</p></div>}</section></>}</section><BottomNav/></main>}
