'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type PlanResult={id:string;name:string;plan_type:string;parse_status:string;is_active:boolean;version_number?:number;effective_from?:string;archived_at?:string|null;raw_extraction:{meals?:Array<{key:string;label:string;foods:Array<{name:string;quantity?:number;unit?:string;raw:string}>}>}};

export default function PlanManager(){
 const supabase=useMemo(()=>createClient(),[]);const[userId,setUserId]=useState<string|null>(null);const[plans,setPlans]=useState<PlanResult[]>([]);const[planType,setPlanType]=useState('standard');const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string|null>(null);const[replaceTarget,setReplaceTarget]=useState<PlanResult|null>(null);
 async function loadPlans(uid:string){const{data}=await supabase.from('nutrition_plans').select('id,name,plan_type,parse_status,is_active,version_number,effective_from,archived_at,raw_extraction').eq('user_id',uid).order('created_at',{ascending:false});setPlans((data??[]) as PlanResult[])}
 useEffect(()=>{void(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){setMessage('Accedi a Miva per gestire il piano nutrizionale.');return}setUserId(data.user.id);await loadPlans(data.user.id)})()},[supabase]);
 async function handleFile(file:File){if(!userId)return;setBusy(true);setMessage(replaceTarget?'Carico la nuova versione del piano…':'Carico e analizzo il piano…');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${userId}/${Date.now()}-${safe}`;const{error:uploadError}=await supabase.storage.from('nutrition-plans').upload(path,file);if(uploadError){setBusy(false);setMessage(`Upload non riuscito: ${uploadError.message}`);return}const type=replaceTarget?.plan_type??planType;const response=await fetch('/api/plan/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,filename:file.name,planType:type,planName:replaceTarget?replaceTarget.name:(type==='on'?'Piano ON':type==='off'?'Piano OFF':file.name.replace(/\.[^.]+$/,'')),supersedesPlanId:replaceTarget?.id})});const result=await response.json();setBusy(false);if(!response.ok){setMessage(result.error??'Analisi non riuscita.');return}setMessage(replaceTarget?`Nuova versione attivata. La versione precedente resta nello storico.`:`Analisi completata: ${result.summary.mealsFound} pasti e ${result.summary.foodsFound} elementi riconosciuti.`);setReplaceTarget(null);await loadPlans(userId)}
 return <main className="planPageShell"><section className="planPage"><header className="planPageHeader"><a href="/" className="backLink">←</a><h1 className="brand">Miva</h1><span/></header><div className="planIntro"><span className="eyebrow">PIANO NUTRIZIONALE</span><h2>Il piano può evolvere.</h2><p>Puoi caricare il piano iniziale oppure sostituirlo dopo una visita. Miva conserva lo storico senza confondere le vecchie versioni con quella attiva.</p></div>{replaceTarget?<div className="replaceBanner"><b>Stai sostituendo:</b><span>{replaceTarget.name} · v{replaceTarget.version_number??1}</span><button onClick={()=>setReplaceTarget(null)}>Annulla</button></div>:<div className="planTypeTabs">{[['standard','Standard'],['on','ON'],['off','OFF']].map(([value,label])=><button key={value} className={planType===value?'active':''} onClick={()=>setPlanType(value)}>{label}</button>)}</div>}<label className={`planDrop ${busy?'busy':''}`}><span className="planDropIcon">⌑</span><strong>{busy?'Sto analizzando…':replaceTarget?'Carica il piano aggiornato':'Carica il piano'}</strong><small>PDF, DOCX, XLS o XLSX</small><input disabled={busy} type="file" accept=".pdf,.docx,.xls,.xlsx" onChange={e=>{const f=e.target.files?.[0];if(f)void handleFile(f)}}/></label>{message?<div className="planMessage">{message}</div>:null}<section className="parsedPlans"><div className="sectionTitleRow"><h3>I tuoi piani</h3><a href="/nutritionist">Da chiedere al nutrizionista</a></div>{plans.length===0?<p className="emptyText">Nessun piano analizzato per ora.</p>:null}{plans.map(plan=><article className={`parsedPlanCard ${!plan.is_active?'archivedPlan':''}`} key={plan.id}><div className="parsedPlanTop"><div><strong>{plan.name}</strong><span>{plan.plan_type.toUpperCase()} · v{plan.version_number??1} · {plan.is_active?'ATTIVO':'STORICO'}</span>{plan.effective_from?<small>Dal {new Date(plan.effective_from).toLocaleDateString('it-IT')}</small>:null}</div><b>{plan.raw_extraction?.meals?.length??0} pasti</b></div><div className="mealExtractList">{(plan.raw_extraction?.meals??[]).map(meal=><div className="mealExtract" key={meal.key}><strong>{meal.label}</strong>{meal.foods.length?<ul>{meal.foods.slice(0,8).map((food,index)=><li key={`${food.raw}-${index}`}><span>{food.name}</span>{food.quantity?<b>{food.quantity} {food.unit}</b>:null}</li>)}</ul>:<small>Nessun alimento riconosciuto automaticamente.</small>}</div>)}</div>{plan.is_active?<button className="secondaryAction replacePlanButton" onClick={()=>setReplaceTarget(plan)}>Sostituisci dopo una visita dal nutrizionista</button>:null}</article>)}</section>{plans.some(p=>p.is_active)?<a className="primaryAction" style={{display:'block',textAlign:'center',textDecoration:'none',marginTop:16}} href="/preferences">Valuta i cibi del piano attivo</a>:null}</section></main>
}
