'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import AppHeader from '@/components/AppHeader'; import BottomNav from '@/components/BottomNav';
type Recipe={id:string;name:string;recipe_origin:string;edit_mode:string;servings:number;prep_minutes:number|null;cook_minutes:number|null;favorite:boolean;plan_compatibility:string};
export default function RecipesView(){const supabase=useMemo(()=>createClient(),[]);const[userId,setUserId]=useState<string|null>(null);const[recipes,setRecipes]=useState<Recipe[]>([]);const[name,setName]=useState('');const[tab,setTab]=useState<'favorites'|'mine'|'miva'>('mine');const[message,setMessage]=useState<string|null>(null);
 async function load(uid:string){const{data,error}=await supabase.from('recipes').select('id,name,recipe_origin,edit_mode,servings,prep_minutes,cook_minutes,favorite,plan_compatibility').eq('user_id',uid).eq('active',true).order('created_at',{ascending:false});if(error)setMessage(error.message);setRecipes((data??[]) as Recipe[])}
 useEffect(()=>{void(async()=>{const{data:a}=await supabase.auth.getUser();if(a.user){setUserId(a.user.id);await load(a.user.id)}})()},[supabase]);
 async function add(){if(!userId||!name.trim())return;const{error}=await supabase.from('recipes').insert({user_id:userId,name:name.trim(),recipe_origin:'user',edit_mode:'ask_each_time',servings:1,plan_compatibility:'unknown'});if(error){setMessage(error.message);return}setName('');await load(userId)}
 const shown=recipes.filter(r=>tab==='favorites'?r.favorite:tab==='mine'?r.recipe_origin==='user':r.recipe_origin==='miva');
 return <main className="shell"><section className="phone withBottomNav"><AppHeader eyebrow="RICETTE"/><div className="sectionTabs"><button className={tab==='favorites'?'active':''} onClick={()=>setTab('favorites')}>Preferiti</button><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>Le mie</button><button className={tab==='miva'?'active':''} onClick={()=>setTab('miva')}>Miva</button></div><section className="heroCard"><h2>Le ricette che userai davvero.</h2><p>Originali, adattabili e preferite restano separate.</p></section>{tab==='mine'?<div className="quickAdd"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome della nuova ricetta"/><button onClick={()=>void add()}>＋</button></div>:null}{message?<div className="planMessage">{message}</div>:null}<section className="recipeList">{shown.length?shown.map(r=><article className="recipeCard" key={r.id}><span className="eyebrow">{r.recipe_origin==='miva'?'RICETTA MIVA':'LA MIA RICETTA'}</span><h3>{r.name}</h3><p>{r.edit_mode==='locked'?'Mantieni originale':r.edit_mode==='adaptable'?'Miva può adattarla':'Chiedimi ogni volta'} · {r.servings} porzione/i</p><small>{r.plan_compatibility==='compatible'?'Compatibile col piano':r.plan_compatibility==='outside'?'Fuori piano':'Compatibilità da verificare'}</small></article>):<div className="emptyStateCard"><strong>Nessuna ricetta qui.</strong><p>{tab==='mine'?'Aggiungi il nome della prima ricetta. Nel prossimo blocco completiamo foto, ingredienti e procedimento.':'Questa sezione si popolerà con preferiti e ricette generate da Miva.'}</p></div>}</section><BottomNav/></section></main>}
