'use client';
import {useEffect,useMemo,useState} from 'react';import {createClient} from '@/lib/supabase/client';import AppHeader from '@/components/AppHeader';import BottomNav from '@/components/BottomNav';
type Item={id:string;food_name:string;brand:string|null;quantity:number|null;unit:string|null;checked:boolean;item_category:string;reason:string|null;suggested:boolean};
export default function ShoppingView(){const supabase=useMemo(()=>createClient(),[]);const[userId,setUserId]=useState<string|null>(null);const[items,setItems]=useState<Item[]>([]);const[name,setName]=useState('');const[nonFood,setNonFood]=useState(false);const[msg,setMsg]=useState<string|null>(null);
 async function load(uid:string){const{data,error}=await supabase.from('shopping_items').select('id,food_name,brand,quantity,unit,checked,item_category,reason,suggested').eq('user_id',uid).order('checked').order('created_at',{ascending:false});if(error)setMsg(error.message);setItems((data??[]) as Item[])}
 useEffect(()=>{void(async()=>{const{data:a}=await supabase.auth.getUser();if(a.user){setUserId(a.user.id);await load(a.user.id)}})()},[supabase]);
 async function add(){if(!userId||!name.trim())return;const{error}=await supabase.from('shopping_items').insert({user_id:userId,food_name:name.trim(),item_category:nonFood?'non_food':'food',source:'manual'});if(error)setMsg(error.message);else{setName('');await load(userId)}}
 async function toggle(i:Item){await supabase.from('shopping_items').update({checked:!i.checked,purchased_at:!i.checked?new Date().toISOString():null}).eq('id',i.id);if(userId)await load(userId)}
 return <main className="shell"><section className="phone withBottomNav"><AppHeader eyebrow="SPESA"/><section className="heroCard"><h2>Compra solo ciò che serve.</h2><p>La lista può essere manuale e, progressivamente, derivata da piano e Dispensa.</p></section><div className="quickAdd shoppingAdd"><input value={name} onChange={e=>setName(e.target.value)} placeholder={nonFood?'Es. detersivo':'Es. yogurt greco'}/><button onClick={()=>void add()}>＋</button></div><label className="tinyToggle"><input type="checkbox" checked={nonFood} onChange={e=>setNonFood(e.target.checked)}/> Prodotto non alimentare</label>{msg?<div className="planMessage">{msg}</div>:null}<section className="shoppingList">{items.length?items.map(i=><button key={i.id} className={`shoppingRow ${i.checked?'checked':''}`} onClick={()=>void toggle(i)}><span>{i.checked?'✓':'○'}</span><div><strong>{i.food_name}</strong><small>{i.item_category==='non_food'?'Casa / non alimentare':i.reason||'Alimentare'}{i.suggested?' · suggerito da Miva':''}</small></div></button>):<div className="emptyStateCard"><strong>Lista vuota.</strong><p>Aggiungi liberamente anche prodotti non alimentari. Per ora Miva non li suggerisce automaticamente.</p></div>}</section><BottomNav/></section></main>}
